"""
🏛️ ceo_agent.py — The Tier 1 Executive: CEO Agent
Reads requirements and writes the master plan into ARCHITECTURE.md.
Uses a Premium LLM brain (Claude/GPT-4o) for massive context windows.
"""

import os
import sys
import logging
from typing import Optional
from datetime import datetime

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
from anatomy.agent_core import BaseAgent, AgentState
from anatomy.brain_dispatcher import query_brain
from database.db_manager import get_agent

logger = logging.getLogger(__name__)

CEO_SOUL = """
[IDENTITY]
You are the CEO of the Paperclip Reborn Foundry. You are a strategic architect, not a coder.
Your role is to read natural-language requirements from the human operator and translate them
into a precise, actionable ARCHITECTURE.md plan that your Tier-2 Cloud Laborers can execute.

[OPERATIONAL RULES]
1. You write ONLY in structured Markdown format.
2. Your plan must be specific enough that a pure-code-output agent can implement it without asking questions.
3. Break large tasks into numbered phases with clear file-level deliverables.
4. For each phase, specify: file path, what to create/modify, and acceptance criteria.
5. Never write code yourself. You architect; they build.
6. Include a Tech Stack section describing the chosen technologies.
7. Include a Task Breakdown section with numbered items that can be fed to a task queue.

[OUTPUT FORMAT]
Output the raw Markdown content for ARCHITECTURE.md. Start with a title, then sections.
Do NOT include any preamble, explanations, or commentary outside the markdown.
"""


class CEOAgent(BaseAgent):
    """
    The CEO — plans architecture, writes ARCHITECTURE.md.
    Now uses the shared brain_dispatcher to call its configured LLM.
    """

    def __init__(self, api_key_env_var: str = "CLAUDE_API_KEY"):
        super().__init__(
            agent_id="ceo",
            agent_name="CEO Agent",
            soul=CEO_SOUL,
            brain="claude-sonnet-4-20250514",
            tier=1,
            hands=["primitive_bash", "primitive_gh"],
        )
        self.api_key = os.getenv(api_key_env_var, "")
        self.workspace_path = os.path.join(
            os.path.dirname(__file__), "..", "shared_workspace"
        )

    def _load_brain(self) -> str:
        """Load the CEO's brain model from the database (UI-configurable)."""
        try:
            agent_data = get_agent("ceo")
            if agent_data and agent_data.get("brain_model"):
                db_model = agent_data["brain_model"]
                self.brain = db_model
                return db_model
        except Exception:
            pass
        return self.brain

    def write_architecture(self, requirements: str) -> str:
        """
        Takes natural-language requirements, sends them to the CEO's LLM brain,
        and writes the generated ARCHITECTURE.md to the shared workspace.

        Falls back to a template if the LLM is unreachable.
        """
        self.set_state(AgentState.INGESTING, "Reading requirements")

        # Load dynamic brain from DB
        model = self._load_brain()
        logger.info("🏛️ CEO brain: %s", model)

        arch_path = os.path.join(self.workspace_path, "ARCHITECTURE.md")

        # Read existing RULES.md for context
        rules_context = ""
        rules_path = os.path.join(self.workspace_path, "RULES.md")
        if os.path.exists(rules_path):
            with open(rules_path, "r", encoding="utf-8") as f:
                rules_context = f"\n\n[RULES.md — You must follow these]\n{f.read()}"

        # Build the prompt
        prompt = f"""You are the CEO. Write a complete ARCHITECTURE.md for the following requirements.

## Requirements from the Operator:

{requirements}

{rules_context}

Now produce the full ARCHITECTURE.md content. Be specific and actionable."""

        self.set_state(AgentState.CODING, "Generating architecture plan via LLM")

        # Call the brain
        response = query_brain(prompt, system=CEO_SOUL, model=model, api_key=self.api_key)

        if response and len(response.strip()) > 50:
            architecture_content = response.strip()
            logger.info("🏛️ CEO generated architecture via %s (%d chars)", model, len(architecture_content))
        else:
            # Fallback: write a structured template if LLM fails
            logger.warning("🏛️ CEO: LLM response empty or too short — using template fallback")
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
            architecture_content = f"""# 🏛️ ARCHITECTURE.md — The CEO's Master Plan

> Auto-generated by CEO Agent ({model}) at {timestamp}
> ⚠️ LLM fallback mode — please review and expand manually.

---

## Current Objective

{requirements}

## Tech Stack
- **Backend:** Python 3.11+ / FastAPI / SQLite
- **Frontend:** React + Vite / Framer Motion
- **Infrastructure:** Docker (QA sandbox), Ollama (local inference)
- **Communication:** Stigmergic (via this repo). No agent-to-agent chat.

## Task Breakdown
1. [ ] Analyze requirements and identify components
2. [ ] Design database schema if applicable
3. [ ] Implement backend endpoints
4. [ ] Build frontend interface
5. [ ] Write tests and validate

## Active Tasks
_Tasks will be populated as the CEO breaks down the objective._
"""

        with open(arch_path, "w", encoding="utf-8") as f:
            f.write(architecture_content)

        logger.info("🏛️ CEO wrote ARCHITECTURE.md")
        self.set_state(AgentState.SUCCESS, "ARCHITECTURE.md written")
        return architecture_content

    def read_architecture(self) -> Optional[str]:
        """Read the current ARCHITECTURE.md contents."""
        arch_path = os.path.join(self.workspace_path, "ARCHITECTURE.md")
        if os.path.exists(arch_path):
            with open(arch_path, "r", encoding="utf-8") as f:
                return f.read()
        return None


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    ceo = CEOAgent()
    content = ceo.write_architecture("Build a REST API for user management with CRUD operations.")
    print(content)

