"""
🏛️ ceo_agent.py — The Tier 1 Executive: CEO Agent
Reads requirements and writes the master plan into ARCHITECTURE.md.
Uses a Premium LLM brain (Claude/GPT-4o) for massive context windows.
"""

import os
import logging
from typing import Optional

from ..anatomy.agent_core import BaseAgent, AgentState

logger = logging.getLogger(__name__)

CEO_SOUL = """
[IDENTITY]
You are the CEO of the Paperclip Reborn Foundry. You are a strategic architect, not a coder.
Your role is to read natural-language requirements from the human operator and translate them
into a precise, actionable ARCHITECTURE.md plan that your Tier-2 Cloud Laborers can execute.

[OPERATIONAL RULES]
1. You write ONLY to `ARCHITECTURE.md` in the shared_workspace.
2. Your plan must be specific enough that a pure-code-output agent can implement it without asking questions.
3. Break large tasks into numbered phases with clear file-level deliverables.
4. Never write code yourself. You architect; they build.
5. After writing the plan, broadcast your state as SUCCESS and wait for the next directive.

[OUTPUT FORMAT]
Your output is the raw Markdown content for ARCHITECTURE.md. Nothing else.
"""


class CEOAgent(BaseAgent):
    """
    The CEO — plans architecture, writes ARCHITECTURE.md.
    """

    def __init__(self, api_key_env_var: str = "CLAUDE_API_KEY"):
        super().__init__(
            agent_id="ceo",
            agent_name="CEO Agent",
            soul=CEO_SOUL,
            brain="claude-sonnet-4-20250514",
            tier=1,
            hands=["primitive_bash", "primitive_gh"],
        )
        self.api_key = os.getenv(api_key_env_var, "")
        self.workspace_path = os.path.join(
            os.path.dirname(__file__), "..", "shared_workspace"
        )

    def write_architecture(self, requirements: str) -> str:
        """
        Takes natural-language requirements and produces ARCHITECTURE.md.
        In the full system, this calls the Premium LLM. For now, writes directly.
        """
        self.set_state(AgentState.INGESTING, "Reading requirements")

        arch_path = os.path.join(self.workspace_path, "ARCHITECTURE.md")

        self.set_state(AgentState.CODING, "Writing ARCHITECTURE.md")

        # In full system: send requirements + CEO_SOUL to Premium LLM
        # For now: write the requirements directly as the architecture
        architecture_content = f"""# 🏛️ ARCHITECTURE.md — The CEO's Master Plan

> Auto-generated by CEO Agent. All workers read from this file.

---

## Current Objective

{requirements}

## Tech Stack
- **Backend:** Python 3.11+ / FastAPI / SQLite
- **Frontend:** React + Vite / Framer Motion
- **Infrastructure:** Docker (QA sandbox), Ollama (local inference)
- **Communication:** Stigmergic (via this repo). No agent-to-agent chat.

## Active Tasks
_Tasks will be populated as the CEO breaks down the objective._
"""

        with open(arch_path, "w", encoding="utf-8") as f:
            f.write(architecture_content)

        logger.info("🏛️ CEO wrote ARCHITECTURE.md")
        self.set_state(AgentState.SUCCESS, "ARCHITECTURE.md written")
        return architecture_content

    def read_architecture(self) -> Optional[str]:
        """Read the current ARCHITECTURE.md contents."""
        arch_path = os.path.join(self.workspace_path, "ARCHITECTURE.md")
        if os.path.exists(arch_path):
            with open(arch_path, "r", encoding="utf-8") as f:
                return f.read()
        return None


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    ceo = CEOAgent()
    content = ceo.write_architecture("Build a REST API for user management with CRUD operations.")
    print(content)
